create database student;
use student;
create table student(
    ID int(5),
    Name varchar(50),
    City varchar(10)
);
create DATABASE doctor;
use doctor;
create table DOCTOR(
    DOCTOR_ID VARCHAR(10) PRIMARY KEY,
    FIRSTNAME VARCHAR( 20),
    LASTNAME VARCHAR(20),
    EMAIL VARCHAR(30) ,
    PHONE INT(10),
    ADDRESS VARCHAR(30)
);
USE STUDENT;
ALTER TABLE student ADD (MOBno BIGINT(10));
DESC STUDENT;
ALTER TABLE STUDENT MODIFY MOBno BIGINT(20);
ALTER TABLE STUDENT RENAME COLUMN ID TO SID;
ALTER TABLE STUDENT DROP COLUMN MOBno;
DROP TABLE DOCTOR PURGE;
CREATE TABLE CUSTOMER(ID INT(10),NAME VARCHAR(20));
DESC CUSTOMER;
TRUNCATE CUSTOMER;
SELECT * FROM STUDENT;
DESC STUDENT;
TRUNCATE STUDENT;
INSERT INTO STUDENT (SID, NAME,CITY)
VALUES(123,'NITIN SHARMA','AJMER'),
(124,'NITIN DFFGFG','AJMER'),
(125,'DFDFG GFGGFG','AJMER');
SELECT *FROM STUDENT;
SELECT SID,City FROM STUDENT;
SELECT NAME,City FROM STUDENT WHERE SID IN(123);
