create database joins;
use joins;
create table Student(ROLL_NO INT(3),NAME VARCHAR(50),ADDRESS VARCHAR(100),PHONE INT(10),AGE INT(3));
ALTER TABLE STUDENT MODIFY COLUMN PHONE BIGINT (10); 
INSERT INTO STUDENT
VALUES 
(1,'HARSH','DELHI',9999999999,18),
(2,'PRATIK','BIHAR',9999999999,19),
(3,'RIYANKA','SILIGURI',9999999999,20),
(4,'DEEP','RAMNAGAR',9999999999,18),
(5,'SAPTARSHI','KOLKATA',9999999999,19),
(6,'DHANRAJ','BARBAJAR',9999999999,20),
(7,'ROHIT','BALURGHAT',9999999999,18),
(1,'NIRAJ','ALIPUR',9999999999,19);
SELECT *FROM STUDENT;
CREATE TABLE StudentCourse (COURSE_ID INT(2),ROLL_NO INT(3));
INSERT INTO StudentCourse
VALUES
(1,1),
(2,2),
(2,3),
(3,4),
(1,5),
(4,9),
(5,10),
(4,11);
SELECT *FROM StudentCourse;
SELECT * FROM StudentCourse;
--INNER JOIN 
SELECT StudentCourse.COURSE_ID,Student.NAME,Student.AGE FROM Student
INNER JOIN StudentCourse
ON Student.ROLL_NO=StudentCourse.ROLL_NO;
--LEFT JOIN
SELECT Student.NAME,StudentCourse.COURSE_ID
FROM Student
LEFT JOIN StudentCourse
ON Student.ROLL_NO=StudentCourse.ROLL_NO;
--RIGHT JOIN
SELECT Student.NAME,StudentCourse.COURSE_ID
FROM Student
RIGHT JOIN StudentCourse
ON Student.ROLL_NO=StudentCourse.ROLL_NO;
--FULL JOIN
SELECT Student.NAME,StudentCourse.COURSE_ID 
FROM Student
FULL JOIN StudentCourse 
ON StudentCourse.ROLL_NO = Student.ROLL_NO;
--NATURAL JOIN
CREATE TABLE Employee (EMP_ID INT(3),EMP_NAME VARCHAR(10),DEPT_ID INT(10));
CREATE TABLE DEPARTMENT(DEPT_ID INT(10),DEPT_NAME VARCHAR(10));
INSERT INTO Employee
VALUES
(1,'RAM',10),
(2,'JON',30),
(3,'BOB',50);
INSERT INTO DEPARTMENT
VALUES
(10,'IT'),
(30,'HR'),
(40,'TIS');
SELECT * FROM Employee
JOIN DEPARTMENT
ON Employee.DEPT_ID=DEPARTMENT.DEPT_ID;